workflows:
  ios-app:
    name: iOS App
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.kantan.bunsho
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Add iOS platform
        script: |
          npx cap add ios || true
          npx cap sync ios
      - name: Configure AdMob for iOS
        script: |
          # Add GADApplicationIdentifier to Info.plist for AdMob
          /usr/libexec/PlistBuddy -c "Add :GADApplicationIdentifier string ca-app-pub-2188494471896935~7089195405" ios/App/App/Info.plist || \
          /usr/libexec/PlistBuddy -c "Set :GADApplicationIdentifier ca-app-pub-2188494471896935~7089195405" ios/App/App/Info.plist
          # Add SKAdNetworkItems for AdMob
          /usr/libexec/PlistBuddy -c "Add :SKAdNetworkItems array" ios/App/App/Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :SKAdNetworkItems:0 dict" ios/App/App/Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :SKAdNetworkItems:0:SKAdNetworkIdentifier string cstr6suwn9.skadnetwork" ios/App/App/Info.plist || true
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
